include_role 'base'

include_cookbook 'ghq'
include_cookbook 'peco'
include_cookbook 'tmux'
include_cookbook 'jq'
include_cookbook 'alp'
include_cookbook 'myprofiler'
include_cookbook 'percona-toolkit'
include_cookbook 'query-digester'
include_cookbook 'sml'
include_cookbook 'netdata'
