#!/bin/bash

set -e

# TODO: Slack Webhook URL を設定する
#export SLACK_WEBHOOK_URL=

# alp で解析
echo
echo ":: ACCESS LOG       ====>"
# TODO: フィルターを良い感じに調整する
sudo cat /var/log/nginx/access.log | alp ltsv -m '^/api/user/\w+/icon$,^/api/livestream/\d+/livecomment$,^/api/livestream/\d+/reaction$,/api/livestream/\d+/livecomment/\d+/report$,/api/livestream/\d+/statistics$,/api/livestream/\d+/report$,/assets/*,/api/livestream/\d+/exit$,/api/livestream/\d+/ngwords$,/api/livestream/\d+/moderate$,/api/livestream/\d+/enter$,/api/user/\w+/theme$,/api/user/\w+/statistics$,/api/user/\w+$,/api/livestream/\d+$,/api/user/\w+/livestream$' --sort=sum -r -o count,uri,min,max,sum,avg | sml
