#!/bin/bash

set -e

# TODO: Slack Webhook URL を設定する
# export SLACK_WEBHOOK_URL=

# alp で解析
echo
echo ":: ACCESS LOG       ====>"
# TODO: フィルターを良い感じに調整する
sudo cat /var/log/nginx/access.log | alp ltsv -m '^/api/organizer/player/\w+/disqualified$,^/api/organizer/competition/\w+/finish$,^/api/organizer/competition/\w+/score$,/api/player/player/\w+$,^/api/player/competition/\w+/ranking$' --sort=sum -r -o count,uri,min,max,sum,avg | sml
