#!/bin/bash

set -e

# nginx のログを削除
echo ":: CLEAR LOGS             ====>"
sudo truncate -s 0 -c /var/log/nginx/access.log

# 各種サービスの再起動
echo
echo ":: RESTART SERVICES       ====>"
# sudo systemctl restart mysql
sudo systemctl restart isuports.service
sudo systemctl restart nginx

# スロークエリログの収集開始
echo
echo ":: COLLECT SLOW QUERY LOG ====>"
